export { default as NavBar } from './NavBar'
export { default as Animations } from './Animations'
// export { default as LottiePlayer } from './LottiePlayer'
export { default as Timer } from './Timer'
export { default as StartButton } from './StartButton'
export { default as PauseButton } from './PauseButton'